root = "."
testdata_dir = "testdata"
tmp_dir = "bin"

[run]
  cmd = "bin/api.exe"

[build]
  args_bin = []
  bin = "bin/api.exe"
  cmd = "go build -o bin/api.exe ./cmd/main.go"
  delay = 300
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "bin", "migrations"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  follow_symlink = false
  full_bin = ""
  include_dir = ["cmd", "pkg", "internal"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = [".env"]
  kill_delay = "2s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = true
  rerun_delay = 300
  send_interrupt = true
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = true
  time = true

[misc]
  clean_on_exit = true

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = true
  keep_scroll = true
